import {
  CircleDot,
  Cloud,
  Compass,
  GitFork,
  Globe2,
  HeartPulse,
  KeyRound,
  LayoutDashboard,
  ListChecks,
  LogIn,
  Network,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  SlidersHorizontal,
  TerminalSquare,
  UserCog,
  UserCircle,
  Users
} from 'lucide-react';

export const sections = [
  { id: 'dashboard', label: 'Dashboard', icon: LayoutDashboard, group: 'Overview' },
  { id: 'logs', label: 'Logs', icon: TerminalSquare, group: 'Overview' },
  { id: 'healthchecks', label: 'Health Checks', icon: HeartPulse, group: 'Overview' },
  { id: 'info', label: 'Info', icon: CircleDot, group: 'Overview' },
  { id: 'services', label: 'Services', icon: Cloud, group: 'Gateway Config' },
  { id: 'instances', label: 'Instances', icon: Server, group: 'Gateway Config' },
  { id: 'routes', label: 'Routes', icon: GitFork, group: 'Gateway Config' },
  { id: 'upstreams', label: 'Upstreams', icon: Network, group: 'Gateway Config' },
  { id: 'api-keys', label: 'API Keys', icon: KeyRound, group: 'Access' },
  { id: 'consumers', label: 'Clients', icon: Users, group: 'Access' },
  { id: 'rate-limits', label: 'Rate Limits', icon: SlidersHorizontal, group: 'Access' },
  { id: 'cors-policies', label: 'CORS Policies', icon: Globe2, group: 'Access' },
  { id: 'security', label: 'Security', icon: Shield, group: 'Access' },
  { id: 'roles', label: 'Roles', icon: ShieldCheck, group: 'Authorization' },
  { id: 'permissions', label: 'Permissions', icon: ListChecks, group: 'Authorization' },
  { id: 'users', label: 'Users', icon: UserCog, group: 'Authorization' },
  { id: 'aggregation', label: 'Aggregation', icon: ListChecks, group: 'Advanced' },
  { id: 'connections', label: 'Connections', icon: Compass, group: 'Advanced' },
  { id: 'settings', label: 'Settings', icon: Settings, group: 'System' },
  { id: 'profile', label: 'Profile', icon: UserCircle, group: 'System' },
  { id: 'login', label: 'Login', icon: LogIn, group: 'System' }
];
